modules.exports = {
    THUNDER_STONE : 'PEDRA DO TROVÃO',
    FIRE_STONE : 'PEDRA DE FOGO',
    WATER_STONE : 'PEDRA DE ÁGUA',
    MOON_STONE : 'PEDRA DA LUA',
    PLANT_STONE : 'PEDRA DA FOLHA',
    NO_EVOLUTION : 'NÃO EVOLUI'
}